# Generated by Django 5.2.17 on 2026-08-13 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('bloodline', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('service_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_monthly_quota', models.SmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'ให้บริการอยู่'), ('INACTIVE', 'ปิดรับชั่วคราว'), ('RETIRED', 'ปลดระวาง')], db_index=True, default='ACTIVE', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeders_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BreederMonthlyQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('max_slots', models.SmallIntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('breeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_quotas', to='breeders.breeder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='breeder',
            constraint=models.CheckConstraint(condition=models.Q(('service_rate__gte', 0)), name='ck_breeder_service_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='breeder',
            constraint=models.CheckConstraint(condition=models.Q(('default_monthly_quota__gte', 0)), name='ck_breeder_default_quota_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='breedermonthlyquota',
            constraint=models.UniqueConstraint(fields=('breeder', 'year', 'month'), name='uq_quota_breeder_year_month'),
        ),
        migrations.AddConstraint(
            model_name='breedermonthlyquota',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 2000)), name='ck_quota_year_gte_2000'),
        ),
        migrations.AddConstraint(
            model_name='breedermonthlyquota',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='ck_quota_month_1_12'),
        ),
        migrations.AddConstraint(
            model_name='breedermonthlyquota',
            constraint=models.CheckConstraint(condition=models.Q(('max_slots__gte', 0)), name='ck_quota_max_slots_gte_0'),
        ),
    ]
