# Generated by Django 5.2.17 on 2026-08-13 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chicks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField()),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('health_status', models.CharField(blank=True, max_length=50, null=True)),
                ('symptom', models.TextField(blank=True, null=True)),
                ('treatment_note', models.TextField(blank=True, null=True)),
                ('chick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='chicks.chick')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_records_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['record_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('weight_grams__gte', 0)), name='ck_health_weight_gte_0')],
            },
        ),
    ]
