# Generated by Django 5.2.17 on 2026-08-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_link_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='line_link_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
