# Generated by Django 5.2.17 on 2026-09-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_line_link_code_user_line_link_code_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='line_link_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='line_link_code_expires_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='line_user_id',
        ),
    ]
