# Generated by Django 5.2.17 on 2026-08-13 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('breed', models.CharField(blank=True, max_length=150, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ใช้งานอยู่'), ('INACTIVE', 'ไม่ใช้งาน')], db_index=True, default='ACTIVE', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
