# Generated by Django 5.2.17 on 2026-08-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hens', '0002_hen_step4_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hen',
            name='ck_hen_age_months_gte_0',
        ),
    ]
