# Generated by Django 5.2.17 on 2026-08-13 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hatching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wing_clip_number', models.CharField(max_length=20, unique=True)),
                ('hatch_date', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'ตัวผู้'), ('FEMALE', 'ตัวเมีย'), ('UNKNOWN', 'ยังไม่ทราบ')], default='UNKNOWN', max_length=10)),
                ('color_note', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ALIVE', 'มีชีวิต'), ('DECEASED', 'ตาย'), ('DELIVERED', 'ส่งมอบแล้ว')], db_index=True, default='ALIVE', max_length=12)),
                ('hatching', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chicks', to='hatching.hatching')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
