# Generated by Django 5.2.17 on 2026-08-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_bookings_bo_booking_f34616_idx'),
        ('chicks', '0002_chick_step7_fields'),
        ('hatching', '0003_hatching_hatching_ha_started_1a2f03_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chick',
            index=models.Index(fields=['birth_date'], name='chicks_chic_birth_d_171bb9_idx'),
        ),
    ]
