# Generated by Django 5.2.17 on 2026-08-13 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chicks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_name', models.CharField(max_length=150)),
                ('vaccine_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('dose', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations_administered', to=settings.AUTH_USER_MODEL)),
                ('chick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='chicks.chick')),
            ],
            options={
                'ordering': ['vaccine_date'],
            },
        ),
    ]
