# Generated by Django 5.2.17 on 2026-08-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunningNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter_type', models.CharField(choices=[('WING_CLIP', 'Wing Clip Number'), ('BOOKING_QUEUE', 'Booking Queue Number'), ('CONTRACT_NO', 'Contract Document Number'), ('PEDIGREE_NO', 'Pedigree Document Number')], max_length=20)),
                ('year', models.SmallIntegerField()),
                ('last_number', models.IntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('counter_type', 'year'), name='uq_counter_type_year'), models.CheckConstraint(condition=models.Q(('last_number__gte', 0)), name='ck_counter_last_number_gte_0')],
            },
        ),
    ]
