# Generated by Django 5.2.17 on 2026-08-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningnumbercounter',
            name='counter_type',
            field=models.CharField(choices=[('WING_CLIP', 'Wing Clip Number'), ('BOOKING_QUEUE', 'Booking Number'), ('CONTRACT_NO', 'Contract Document Number'), ('PEDIGREE_NO', 'Pedigree Document Number'), ('PAYMENT_NO', 'Payment Number')], max_length=20),
        ),
    ]
