# Generated by Django 5.2.17 on 2026-08-13 05:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('chicks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_type', models.CharField(choices=[('CONTRACT', 'ใบรับฝากผสม/สัญญา'), ('PEDIGREE_CERTIFICATE', 'ใบรับรองสายพันธุ์'), ('DELIVERY_HISTORY', 'เอกสารส่งมอบ')], db_index=True, max_length=25)),
                ('document_no', models.CharField(max_length=30, unique=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bookings.booking')),
                ('chick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chicks.chick')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('chick__isnull', True), ('document_type', 'CONTRACT')), models.Q(('chick__isnull', False), ('document_type__in', ['PEDIGREE_CERTIFICATE', 'DELIVERY_HISTORY'])), _connector='OR'), name='ck_document_ownership_by_type')],
            },
        ),
    ]
