# Generated by Django 5.2.17 on 2026-08-13 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('DEPOSIT', 'มัดจำ'), ('FULL', 'เต็มจำนวน'), ('ADDITIONAL', 'ชำระเพิ่มเติม')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slip_image_path', models.CharField(max_length=255)),
                ('paid_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'รอตรวจสอบ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ปฏิเสธ')], db_index=True, default='PENDING_REVIEW', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING_REVIEW')), fields=('booking', 'payment_type'), name='uq_payment_pending_type'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payment_amount_gt_0')],
            },
        ),
    ]
