# Generated by Django 5.2.17 on 2026-08-17 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_bookings_bo_booking_f34616_idx'),
        ('payments', '0003_alter_payment_verified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='payments_pa_paid_at_b40014_idx'),
        ),
    ]
