# Generated by Django 5.2.17 on 2026-08-13 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('RECEIVED_AT_FARM', 'รับเข้าฟาร์ม'), ('PAIRED', 'เข้าคู่ผสม'), ('EGG_LAYING', 'ออกไข่'), ('MOVED_TO_INCUBATOR', 'ย้ายเข้าตู้ฟัก'), ('COMPLETED', 'เสร็จสิ้น')], max_length=20)),
                ('event_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='bookings.booking')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_events_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'stage'), name='uq_timeline_booking_stage')],
            },
        ),
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lay_date', models.DateField()),
                ('egg_count', models.SmallIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eggs', to='bookings.booking')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eggs_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('egg_count__gte', 0)), name='ck_egg_count_gte_0')],
            },
        ),
    ]
