# Generated by Django 5.2.17 on 2026-08-17 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_bookings_bo_booking_f34616_idx'),
        ('breeding', '0002_breeding_step6_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='breedingevent',
            index=models.Index(fields=['event_date'], name='breeding_br_event_d_0fdde7_idx'),
        ),
        migrations.AddIndex(
            model_name='egg',
            index=models.Index(fields=['egg_date'], name='breeding_eg_egg_dat_7b215d_idx'),
        ),
    ]
