# Generated by Django 5.2.17 on 2026-09-16 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_insemination_record'),
        ('breeding', '0003_breedingevent_breeding_br_event_d_0fdde7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InseminationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_number', models.SmallIntegerField()),
                ('record_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inseminations', to='bookings.booking')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inseminations_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['record_date', 'session_number'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'session_number'), name='uq_insemination_booking_session')],
            },
        ),
    ]
