# Generated by Django 5.2.17 on 2026-08-13 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hatch_start_date', models.DateField(blank=True, null=True)),
                ('hatch_end_date', models.DateField(blank=True, null=True)),
                ('hatched_count', models.SmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('INCUBATING', 'กำลังฟัก'), ('HATCHED', 'ฟักออกแล้ว'), ('FAILED', 'ฟักไม่สำเร็จ')], db_index=True, default='INCUBATING', max_length=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('egg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatchings', to='breeding.egg')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hatchings_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('hatched_count__gte', 0)), name='ck_hatching_count_gte_0')],
            },
        ),
    ]
