# Generated by Django 5.2.17 on 2026-08-17 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0003_breedingevent_breeding_br_event_d_0fdde7_idx_and_more'),
        ('hatching', '0002_hatching_step7_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hatching',
            index=models.Index(fields=['started_at'], name='hatching_ha_started_1a2f03_idx'),
        ),
    ]
