# Generated by Django 5.2.17 on 2026-08-13 05:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeders', '0001_initial'),
        ('hens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking_year', models.SmallIntegerField()),
                ('booking_month', models.SmallIntegerField()),
                ('queue_no', models.SmallIntegerField(blank=True, null=True)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'รอชำระเงินมัดจำ'), ('WAITING_APPROVAL', 'รออนุมัติ'), ('APPROVED_LOCKED', 'อนุมัติแล้ว/ล็อกคิว'), ('IN_PROGRESS', 'กำลังดำเนินการผสม'), ('COMPLETED', 'เสร็จสิ้น'), ('REJECTED', 'ปฏิเสธ'), ('CANCELLED', 'ยกเลิก')], db_index=True, default='PENDING_PAYMENT', max_length=20)),
                ('current_breeding_stage', models.CharField(blank=True, choices=[('RECEIVED_AT_FARM', 'รับเข้าฟาร์ม'), ('PAIRED', 'เข้าคู่ผสม'), ('EGG_LAYING', 'ออกไข่'), ('MOVED_TO_INCUBATOR', 'ย้ายเข้าตู้ฟัก'), ('COMPLETED', 'เสร็จสิ้น')], max_length=20, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_approved', to=settings.AUTH_USER_MODEL)),
                ('breeder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='breeders.breeder')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_cancelled', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('hen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hens.hen')),
            ],
            options={
                'indexes': [models.Index(fields=['breeder', 'booking_year', 'booking_month'], name='bookings_bo_breeder_987cc9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING_PAYMENT', 'WAITING_APPROVAL', 'APPROVED_LOCKED', 'IN_PROGRESS'])), fields=('hen',), name='uq_booking_hen_active'), models.UniqueConstraint(condition=models.Q(('status__in', ['CANCELLED', 'REJECTED']), _negated=True), fields=('hen', 'breeder', 'booking_year', 'booking_month'), name='uq_booking_no_duplicate_request'), models.UniqueConstraint(condition=models.Q(('queue_no__isnull', False)), fields=('breeder', 'booking_year', 'booking_month', 'queue_no'), name='uq_booking_queue_slot'), models.CheckConstraint(condition=models.Q(('booking_month__gte', 1), ('booking_month__lte', 12)), name='ck_booking_month_1_12'), models.CheckConstraint(condition=models.Q(('deposit_amount__gte', 0), ('deposit_amount__lte', models.F('agreed_price'))), name='ck_booking_deposit_between_0_and_price'), models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='ck_booking_amount_paid_gte_0'), models.CheckConstraint(condition=models.Q(('balance_due__gte', 0)), name='ck_booking_balance_due_gte_0')],
            },
        ),
    ]
