# Generated by Django 5.2.17 on 2026-08-17 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_step5_fields'),
        ('breeders', '0002_breeder_step4_fields'),
        ('hens', '0003_remove_redundant_age_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='bookings_bo_booking_f34616_idx'),
        ),
    ]
