# Generated by Django 5.2.17 on 2026-09-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_bookings_bo_booking_f34616_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='brooding_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hen_brooding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('WAITING_PAYMENT', 'รอชำระเงิน'), ('PAID', 'ชำระเงินแล้ว'), ('APPROVED', 'อนุมัติแล้ว/ล็อกคิว'), ('IN_PROGRESS', 'กำลังดำเนินการผสม'), ('COMPLETED', 'เสร็จสิ้น'), ('CANCELLED', 'ยกเลิก'), ('REJECTED', 'ปฏิเสธ')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
