# Generated by Django 5.2.17 on 2026-08-17 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_bookings_bo_booking_f34616_idx'),
        ('chicks', '0003_chick_chicks_chic_birth_d_171bb9_idx'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('retry_count__gte', 0)), name='ck_notification_retry_count_gte_0'),
        ),
    ]
