# Generated by Django 5.2.17 on 2026-09-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_retry_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(default='EMAIL', max_length=10),
        ),
    ]
