# Generated by Django 5.2.17 on 2026-08-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_linelinkcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
